# NumPy basics

This notebook stands for introduction to and presentation of NumPy - powerful Python library
for numerical computation.

### What does NumPy contain?

NumPy provides tools for conducting numerical computations in Python. It allows to do it
faster and more conveniently.

Basically, NumPy provides:

- n-dimensional arrays (_ndarrays_)
- functions to manipulate these arrays

By convention, we import NumPy using _np_ alias.

In [1]:
import numpy as np

In [3]:
some_array = np.array([0,1,2,3,4,5,6])
print(some_array)

[0 1 2 3 4 5 6]


### ndarray

Multidimensional array class in NumPy is _ndarray_ (also known as _array_, which is its alias).
It is an array that contain elements of one type and can have many dimensons.

In [4]:
# example array - np.array() function creates array from a sequence
one_dim_array = np.array([1,2,3,4])
print(one_dim_array)

[1 2 3 4]


In [10]:
# two dimensional array - lists of lists
two_dim_array = np.array([[11, 12, 13],
                         [21, 22, 23],
                         [31, 32, 33]])
print(two_dim_array)
print('\n')
# can be more dimensions - analogously
three_dim_array = np.array([
                             [[111, 112, 113],
                             [121, 122, 123],
                             [131, 132, 133]],
                            [[211, 212, 213],
                             [221, 222, 223],
                             [231, 232, 233]]
                           ])
print(three_dim_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


[[[111 112 113]
  [121 122 123]
  [131 132 133]]

 [[211 212 213]
  [221 222 223]
  [231 232 233]]]


We have three arrays objects above - _one_dim_array_ has one dimension, _two_dim_array_ has two dimensions and _three_dim_array_ is three-dimensional.

n-dimensional ndarray has n _axes_ (0, 1, ..., n-1), each axes is a _direction_ towards some dimension.

Important thing: the axis printed from left to right is the _last_ axis, next are printed from top to bottom.

For example, _three_dim_array_ can be thought as two matrices with numbered matrices, matrices rows and matrices columns. Axis 2 (last axis) goes through numbers of matrices columns. Axis 1 goes through numbers of matrices rows. Axis 0 goes through numbers of matrices.

We demontrate this by calculating sums of elements over each axis.

In [12]:
# sum over axis 2 - each element stands for one matrix' one row sum
# (because axis goes through numbers of matrix' columns)
np.sum(three_dim_array, axis=2)

array([[336, 366, 396],
       [636, 666, 696]])

In [13]:
np.sum(three_dim_array, axis=1)

array([[363, 366, 369],
       [663, 666, 669]])

In [14]:
np.sum(three_dim_array, axis=0)

array([[322, 324, 326],
       [342, 344, 346],
       [362, 364, 366]])

We can see array's properties.

In [15]:
# number of dimensions
three_dim_array.ndim

3

In [17]:
# number of elements in each dimension (over each axis)
three_dim_array.shape

(2, 3, 3)

In [18]:
# number of bytes one element occupy
three_dim_array.itemsize

4

In [19]:
# total size in bytes
three_dim_array.nbytes

72