# NumPy basics

This notebook stands for introduction to and presentation of NumPy - powerful Python library
for numerical computation.

### What does NumPy contain?

NumPy provides tools for conducting numerical computations in Python. It allows to do it
faster and more conveniently.

Basically, NumPy provides:

- n-dimensional arrays (_ndarrays_)
- functions to manipulate these arrays

By convention, we import NumPy using _np_ alias.

In [1]:
import numpy as np

In [2]:
some_array = np.array([0,1,2,3,4,5,6])
print(some_array)

[0 1 2 3 4 5 6]


### ndarray

Multidimensional array class in NumPy is _ndarray_ (also known as _array_, which is its alias).
It is an array that contain elements of one type and can have many dimensons.

In [3]:
# example array - np.array() function creates array from a sequence
one_dim_array = np.array([1,2,3,4])
print(one_dim_array)

[1 2 3 4]


In [4]:
# two dimensional array - lists of lists
two_dim_array = np.array([[11, 12, 13],
                         [21, 22, 23],
                         [31, 32, 33]])
print(two_dim_array)
print('\n')
# can be more dimensions - analogously
three_dim_array = np.array([
                             [[111, 112, 113],
                             [121, 122, 123],
                             [131, 132, 133]],
                            [[211, 212, 213],
                             [221, 222, 223],
                             [231, 232, 233]]
                           ])
print(three_dim_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


[[[111 112 113]
  [121 122 123]
  [131 132 133]]

 [[211 212 213]
  [221 222 223]
  [231 232 233]]]


We have three arrays objects above - _one_dim_array_ has one dimension, _two_dim_array_ has two dimensions and _three_dim_array_ is three-dimensional.

n-dimensional ndarray has n _axes_ (0, 1, ..., n-1), each axes is a _direction_ towards some dimension.

Important thing: the axis printed from left to right is the _last_ axis, next are printed from top to bottom.

For example, _three_dim_array_ can be thought as two matrices with numbered matrices, matrices rows and matrices columns. Axis 2 (last axis) goes through numbers of matrices columns. Axis 1 goes through numbers of matrices rows. Axis 0 goes through numbers of matrices.

We demontrate this by calculating sums of elements over each axis.

In [5]:
# sum over axis 2 - each element stands for one matrix' one row sum
# (because axis goes through numbers of matrix' columns)
np.sum(three_dim_array, axis=2)

array([[336, 366, 396],
       [636, 666, 696]])

In [6]:
np.sum(three_dim_array, axis=1)

array([[363, 366, 369],
       [663, 666, 669]])

In [7]:
np.sum(three_dim_array, axis=0)

array([[322, 324, 326],
       [342, 344, 346],
       [362, 364, 366]])

We can see array's properties.

In [8]:
# number of dimensions
three_dim_array.ndim

3

In [9]:
# number of elements in each dimension (over each axis)
three_dim_array.shape

(2, 3, 3)

In [10]:
# number of bytes one element occupy
three_dim_array.itemsize

4

In [11]:
# total size in bytes
three_dim_array.nbytes

72

### Data types

In a NumPy array all of the elements has to be the same type. The type of an array object is called _dtype_.

In [12]:
# data type
three_dim_array.dtype

dtype('int32')

We can fit datatype to our purpose.

In [13]:
# 16-bit int
sixteen = np.array([5,3,5,3], dtype='int16')
print(sixteen.dtype)
print(sixteen.itemsize)

int16
2


In [14]:
# 32-bit floating point number
single_prec = np.array([[4.5, 7.86,],
                        [5.0, 1.25]], dtype='float32')
print(single_prec.dtype)
print(single_prec.itemsize)

float32
4


In [15]:
string_array = np.array(['gf', 'hh', 'as'])
string_array.dtype

dtype('<U2')

We can create _structured data types_, which are aggregates of other data types.

In [16]:
# data type object
np.dtype([('f1', np.uint32), ('f2', np.float_)])

dtype([('f1', '<u4'), ('f2', '<f8')])

### Create an array

In [17]:
# np.array() function
arr = np.array([[1,2,3,4], [3,2,1,3]])
arr

array([[1, 2, 3, 4],
       [3, 2, 1, 3]])

In [18]:
# using function on indices
np.fromfunction(lambda i, j: i >= j, (3,3), dtype=int)

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [19]:
# using iterable object (only 1-d)
# count parameter enhances speed
np.fromiter((i**2 for i in range(5)), dtype='int32', count=5)

array([ 0,  1,  4,  9, 16])

In [20]:
# create array filled with zeros...

# ...of desired shape
print(np.zeros((5,2)))

# ...of the same shape as another array
print(np.zeros_like(two_dim_array))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
# create array filled with ones
print(np.ones((5,2)))
print(np.ones_like(two_dim_array))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [22]:
# or filled with any other number
print(np.full((5,2), 3.14))
print(np.full_like(two_dim_array, 3.14))
# caution! data type

[[3.14 3.14]
 [3.14 3.14]
 [3.14 3.14]
 [3.14 3.14]
 [3.14 3.14]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [23]:
# create array with some values dependent on memory that are to be replaced
np.empty((1,2))  # may vary

array([[8.35850647e-312, 0.00000000e+000]])